
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/",
]
# means stateful fuzz testing. Running random data on to many functions within your contract
[invariant]
run = 128
depth = 128
fail_on_revert = true
# number of calls in a single run

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-optionsruns = 128  # number of runs
